"""
Build standalone .exe for WD Word Counter
"""

import os
import subprocess
import sys
from pathlib import Path

def build_with_pyinstaller():
    """Build .exe using PyInstaller"""
    
    print("Building WD Word Counter executable...")
    
    # Build Rust backend first
    print("\n1. Building Rust backend...")
    rust_result = subprocess.run(
        ["cargo", "build", "--release"],
        capture_output=True,
        text=True
    )
    
    if rust_result.returncode != 0:
        print("Failed to build Rust backend:")
        print(rust_result.stderr)
        return False
    
    print("✓ Rust backend built")
    
    # Copy Rust library
    if sys.platform == "win32":
        rust_lib = "target/release/wdlib.dll"
        dest_lib = "wdlib.pyd"
    else:
        print("Non-Windows platform detected, building for current OS")
        rust_lib = "target/release/libwdlib.so"
        dest_lib = "wdlib.so"
    
    import shutil
    shutil.copy2(rust_lib, dest_lib)
    print("✓ Rust library copied")
    
    # Create PyInstaller spec
    spec_content = f'''
# -*- mode: python ; coding: utf-8 -*-
import sys
import os

block_cipher = None

a = Analysis(
    ['WD.py'],
    pathex=[os.getcwd()],
    binaries=[],
    datas=[
        ('{dest_lib}', '.'),
        ('assets', 'assets'),
    ],
    hiddenimports=['src.ui_mainwindow'],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WD',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico' if os.path.exists('assets/icon.ico') else None,
)
'''
    
    with open("WD.spec", "w") as f:
        f.write(spec_content)
    
    print("✓ PyInstaller spec created")
    
    # Run PyInstaller
    print("\n2. Running PyInstaller...")
    result = subprocess.run(
        ["pyinstaller", "--clean", "WD.spec"],
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        print("\n" + "="*50)
        print("✓ BUILD SUCCESSFUL!")
        print("="*50)
        print(f"\nExecutable created at: dist/WD.exe")
        print("\nYou can run it directly or distribute it.")
        return True
    else:
        print("\n✗ BUILD FAILED:")
        print(result.stderr)
        return False

def create_installer():
    """Create NSIS installer for Windows"""
    if sys.platform != "win32":
        print("NSIS installer only available on Windows")
        return
    
    print("\nCreating NSIS installer...")
    
    nsis_script = r'''
; WD Word Counter Installer
; Generated by build_exe.py

!include "MUI2.nsh"

; Basic installer settings
Name "WD Word Counter"
OutFile "WD_Setup.exe"
InstallDir "$PROGRAMFILES\WD Word Counter"
InstallDirRegKey HKLM "Software\WD" "Install_Dir"
RequestExecutionLevel admin

; Interface settings
!define MUI_ABORTWARNING

; Pages
!insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "English"

; Installer sections
Section "WD Word Counter" SecMain
    SectionIn RO
    
    SetOutPath "$INSTDIR"
    
    ; Files to install
    File "dist\WD.exe"
    File "wdlib.pyd"
    
    ; Create start menu shortcuts
    CreateDirectory "$SMPROGRAMS\WD Word Counter"
    CreateShortcut "$SMPROGRAMS\WD Word Counter\WD.lnk" "$INSTDIR\WD.exe"
    CreateShortcut "$SMPROGRAMS\WD Word Counter\Uninstall.lnk" "$INSTDIR\uninstall.exe"
    CreateShortcut "$DESKTOP\WD Word Counter.lnk" "$INSTDIR\WD.exe"
    
    ; Write registry keys
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\WD" \
        "DisplayName" "WD Word Counter"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\WD" \
        "UninstallString" '"$INSTDIR\uninstall.exe"'
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\WD" \
        "NoModify" 1
    WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\WD" \
        "NoRepair" 1
    
    ; Write uninstaller
    WriteUninstaller "$INSTDIR\uninstall.exe"
SectionEnd

Section "Start Menu Shortcut" SecShortcut
    ; Already created in main section
SectionEnd

Section "Desktop Shortcut" SecDesktop
    ; Already created in main section
SectionEnd

; Uninstaller
Section "Uninstall"
    ; Remove shortcuts
    Delete "$SMPROGRAMS\WD Word Counter\WD.lnk"
    Delete "$SMPROGRAMS\WD Word Counter\Uninstall.lnk"
    Delete "$DESKTOP\WD Word Counter.lnk"
    RMDir "$SMPROGRAMS\WD Word Counter"
    
    ; Remove files
    Delete "$INSTDIR\WD.exe"
    Delete "$INSTDIR\wdlib.pyd"
    Delete "$INSTDIR\uninstall.exe"
    RMDir "$INSTDIR"
    
    ; Remove registry keys
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\WD"
    DeleteRegKey HKLM "Software\WD"
SectionEnd

; Section descriptions
LangString DESC_SecMain ${LANG_ENGLISH} "WD Word Counter application files."
LangString DESC_SecShortcut ${LANG_ENGLISH} "Create Start Menu shortcut."
LangString DESC_SecDesktop ${LANG_ENGLISH} "Create Desktop shortcut."

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
    !insertmacro MUI_DESCRIPTION_TEXT ${SecMain} $(DESC_SecMain)
    !insertmacro MUI_DESCRIPTION_TEXT ${SecShortcut} $(DESC_SecShortcut)
    !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} $(DESC_SecDesktop)
!insertmacro MUI_FUNCTION_DESCRIPTION_END
'''
    
    with open("installer.nsi", "w") as f:
        f.write(nsis_script)
    
    print("✓ NSIS script created")
    print("\nTo create installer, run:")
    print("makensis installer.nsi")

if __name__ == "__main__":
    print("WD Word Counter Builder")
    print("=" * 50)
    
    success = build_with_pyinstaller()
    
    if success and sys.platform == "win32":
        create = input("\nCreate Windows installer? (y/n): ")
        if create.lower() == 'y':
            create_installer()